### ISSUE TITLE
Add ability to invalidate individual cache records

### ISSUE THREAD

**Issue by fergmastaflex** [abrandoned/active_remote-cached#7]
Adding this functionality would allow us to invalidate specific records by using subscribers. Whenever a record is updated, we can clear it from the cache as needed.

@liveh2o @mmmries @abrandoned

**Comment by abrandoned** [comment]
These methods are already present; anything that has a method of "find_by_" also has a "delete_by"

https://github.com/abrandoned/active_remote-cached/blob/master/lib/active_remote/cached.rb#L133

https://github.com/abrandoned/active_remote-cached/blob/master/spec/active_remote/cached_delete_methods_spec.rb#L15
